# Generated by Django 5.1.6 on 2025-03-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_remove_bouquetofflowers_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
    ]
