# Generated by Django 5.1.6 on 2025-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exclude_flowers',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='flowers.flower'),
        ),
    ]
